url: http://maxime-besson.fr


# Site settings
title: MB.
email: contact@maxime-besson.fr
description: "Développeur web et conférences scolaires à Angers dans le Maine et Loire. Sites vitrines, boutiques en ligne, référencement naturel (SEO), webmarketing et conférences pour les collèges, lycées, universités."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 34495e
  secondary: 2c3e50  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Maxime B
  pic: 2
  position: Développeur web - Conférences scolaires
  social:
  - title: linkedin
    url: http://fr.linkedin.com/in/bessonmaxime

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://fr.linkedin.com/in/bessonmaxime

# Build settings
markdown: kramdown
permalink: pretty